# Permalinks
permalink:      pretty

# Setup
title:          DDIS UAG
description:    Data-Driven and Innovation Services - Universitas Ary Ginanjar.
baseurl:        
url:            "https://prodisi-uag.github.io/ddis-uag/"

color:          link

author:
  name:         DDIS UAG
  url:          https://prodisi-uag.github.io/ddis-uag/
  email:                                           # Place your email here
  github:       https://github.com/prodiSI-UAG                    # Place your GitHub username here
#  twitter:      Linuxneitor                        # Place your twitter username here
#  mastodon:     https://mastodon.social/@jsalvador # Place your profile URL here

twitter:
  username: Linuxneitor
  card: summary
locale: es_ES

# Assets
sass:
  style:        compressed

markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM

# Custom vars
version:        4.3.3
paginate:       5                                  # Default pagination is 5 post per page
paginate_path: "/page:num/"

plugins: 
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-feed
